[build]
  # Build command (statik HTML olduğu için boş bırakıyoruz)
  command = ""
  
  # Publish directory (dosyalarının bulunduğu klasör)
  publish = "."

[build.environment]
  # Node.js versiyonu (gerekirse)
  NODE_VERSION = "18"

# Redirect rules (SPA için)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers (güvenlik ve performans için)
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom domain ayarları (isteğe bağlı)
# [context.production]
#   command = ""
#   publish = "."

# Branch-specific ayarları (isteğe bağlı)
[context.deploy-preview]
  command = ""
  publish = "."

[context.branch-deploy]
  command = ""
  publish = "."